# Generated by Django 3.2.16 on 2022-10-28 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('rating', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Movies',
            fields=[
                ('movie_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=400)),
                ('release_date', models.DateField()),
                ('image', models.URLField()),
                ('rating', models.ManyToManyField(to='movies.User')),
            ],
        ),
        migrations.CreateModel(
            name='Actors',
            fields=[
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('actor_id', models.AutoField(primary_key=True, serialize=False)),
                ('movies', models.ManyToManyField(to='movies.Movies')),
            ],
        ),
    ]
