# Generated by Django 3.2.16 on 2022-10-28 19:38

from django.db import migrations

def add_item(apps, editor):
    Movies = apps.get_model('movies', 'Movies')
    movie = Movies(title='The Matrix', release_date='1999-03-31', image='https://upload.wikimedia.org/wikipedia/en/c/c1/The_Matrix_Poster.jpg')
    movie.save()

class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(add_item),
    ]
