# Generated by Django 3.2.16 on 2022-10-28 20:13

from django.db import migrations

def add_actor(apps, editor):
    Actor = apps.get_model('movies', 'Actors')
    Movie = apps.get_model('movies', 'Movies')
    actor = Actor(first_name='Keanu', last_name='Reeves')
    actor.save()
    movie = Movie.objects.get(movie_id=1)
    actor.movies.add(movie)

class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_auto_20221028_1938'),
    ]

    operations = [
        migrations.RunPython(add_actor),
    ]
