# Generated by Django 3.2.16 on 2022-11-01 00:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_auto_20221028_2013'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='movie',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='movies.movies'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.CharField(default='Anon', max_length=50),
            preserve_default=False,
        ),
    ]
