# Generated by Django 3.2.16 on 2022-11-01 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_auto_20221101_0026'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Review',
        ),
    ]
