# Generated by Django 4.1.3 on 2022-11-24 02:10

from django.db import migrations
from tqdm import tqdm

import csv

def add_item(apps, editor):
    #read movies data file into lists of the movie title, movie id, and movie year
    with open('new_movies.tsv', mode ='r', encoding= "utf-8") as file:
        # reading the CSV file
        csv_reader = csv.reader(file, delimiter= "\t")
        for x, line in tqdm(enumerate(csv_reader), total=627521):
            if x == 0:
                continue
            #add movie title to movie title listß
            Movies = apps.get_model('movies', 'Movies')
            movie = Movies(imdb_id=line[0], title=line[2], release_date=line[5], image='https://upload.wikimedia.org/wikipedia/en/c/c1/The_Matrix_Poster.jpg')
            movie.save()
            x = x+1

class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0006_alter_movies_release_date'),
    ]

    operations = [
        migrations.RunPython(add_item),
    ]
