# Generated by Django 4.1.3 on 2022-11-24 02:10

from django.db import migrations

import csv

def add_item(apps, editor):
    #read movies data file into lists of the movie title, movie id, and movie year
    with open('movies.tsv', mode ='r', encoding= "utf-8") as file:
        # reading the CSV file
        csv_reader = csv.reader(file, delimiter= "\t")
        #list to hold all movie titles
        #movietitle = []
        #list to hold all movie ids
        #movieid = []
        #list to hold movie years
        #year = []

        #place holder for the first row to be skipped
        x = 0
        #to hold the int value of the movie id
        #y = 0
        for line in csv_reader:
            if x == 0:
                x = x+1
            else:
                if line[1] == 'movie':
                    #add movie title to movie title list
                    #movietitle.append(line[2])
                    Movies = apps.get_model('movies', 'Movies')
                    movie = Movies(title=line[2], release_date=line[5], image='https://upload.wikimedia.org/wikipedia/en/c/c1/The_Matrix_Poster.jpg')
                    movie.save()

                    #filter through the characters in the movie id, keeping only the values that make up the movie id 
                    """
                    emp_str=""
                    for m in line[0]:
                        if m.isdigit():
                            emp_str=emp_str + m
                    y = int(emp_str)

                    #add movie id to movieid list
                    movieid.append(y)
                    #add year release to year list
                    year.append(line[5])
                    """

                    #check the data in lists

                    #print (movieid[x-1])
                    #print (movietitle[x-1])
                    #print (year[x-1])

                    #increment x by one, so indecate that we have just passed the first row
                    x = x+1

class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0006_alter_movies_release_date'),
    ]

    operations = [
        migrations.RunPython(add_item),
    ]
