# Generated by Django 3.2.16 on 2022-11-25 19:24

from django.db import migrations

def remove_item(apps, editor):
    Movies = apps.get_model('movies', 'Movies')
    movie = Movies.objects.get(movie_id=1)
    movie.delete()

class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0007_auto_20221123_2110'),
    ]

    operations = [
        migrations.RunPython(remove_item),
    ]
