# Generated by Django 3.2.16 on 2022-11-25 20:57

from django.db import migrations

def remove_actor(apps, editor):
    Actor = apps.get_model('movies', 'Actors')
    actor = Actor.objects.get(actor_id=1)
    actor.delete()

class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0008_delete_item_one'),
    ]

    operations = [
        migrations.RunPython(remove_actor),
    ]
