# Generated by Django 4.1.3 on 2022-11-25 03:10

from django.db import migrations

import csv

def add_actor(apps, editor):
    with open('new_actors.tsv', mode ='r', encoding= "utf-8") as file:
        
       # reading the CSV file
       csv_reader = csv.reader(file, delimiter= "\t")

       #place holder for the first row which is the header row for the tsv file
       x = 0
       for line in csv_reader:
        #skip the first row
        if x == 0:
            x = x+1
        else:
            #empty string to hold characters of the movie ids acotr acted in
            empm_str=""

            #save the name of the actors
            Actor = apps.get_model('movies', 'Actors')
            Movie = apps.get_model('movies', 'Movies')
            actor = Actor(first_name=line[1], last_name=' ')
            actor.save()

            #seperate movie ids and add each movie
            for n in line[5]:
                if (n != ','):
                    empm_str=empm_str + n
                elif(n == ','):
                    #add movie
                    movie = Movie.objects.get(imbd_id= empm_str)
                    actor.movies.add(movie)
                    #reset id to find next movie id
                    empm_str=""

            #add last movie id this actor has acted in
            movie = Movie.objects.get(imbd_id = empm_str)
            actor.movies.add(movie)
            
            #increment x by one, to indicate that we have just passed the first row
            x = x+1
class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0007_auto_20221123_2110'),
    ]

    operations = [
        migrations.RunPython(add_actor),
    ]