# Generated by Django 3.2.16 on 2022-11-26 16:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0010_create_search_procedure'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actors',
            name='movies',
        ),
        migrations.CreateModel(
            name='ActorMovies',
            fields=[
                ('imdb_id', models.CharField(max_length=20, null=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.actors')),
            ],
        ),
    ]
