# Generated by Django 3.2.16 on 2022-11-27 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0012_add_actors'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movies',
            name='image',
        ),
    ]
