# Generated by Django 3.2.16 on 2022-11-27 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0013_remove_movies_image'),
    ]

    operations = [
        migrations.RunSQL("""
            CREATE INDEX actor_names ON movies_actors (first_name, last_name);
            """),
    ]
