# Generated by Django 3.2.16 on 2022-11-28 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0014_create_index'),
    ]

    operations = [
        migrations.RunSQL("""
            DROP FUNCTION search_movies;
            CREATE OR REPLACE FUNCTION search_movies(search_text text)
            RETURNS TABLE(movie_id integer, release_date text, title text, imdb_id text) AS $$
            BEGIN
                RETURN QUERY
                SELECT * FROM movies_movies WHERE LOWER(title) 
                LIKE '%' || search_text || '%' OR 
                release_date LIKE '%' || search_text || '%' OR
                imdb_id LIKE '%' || search_text || '%'
                ORDER BY movie_id DESC;
            END;
            $$ LANGUAGE plpgsql;
            """)
    ]
