# Generated by Django 3.2.16 on 2022-11-28 16:06

from django.db import migrations

class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0015_update_search_procedure'),
    ]

    operations = [
        migrations.RunSQL("""
        DELETE FROM movies_movies WHERE LOWER(title) LIKE '%' || 'sex' || '%' OR LOWER(title) LIKE '%' || 'xxx' || '%';
        """),
    ]
