# Generated by Django 3.2.16 on 2022-11-28 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0016_nsfw_filter'),
    ]

    operations = [
        migrations.RunSQL("""
            CREATE PROCEDURE insert_movie(title varchar, release_date varchar, imdb_id varchar)
            LANGUAGE plpgsql
            AS $$
            BEGIN
                INSERT INTO movies_movies (title, release_date, imdb_id)
                VALUES (title, release_date, imdb_id);
            END;
            $$;
        """),
    ]
